---
- name: Ensure config directory
  file:
    state: directory
    path: "{{ prometheus_config_dir }}/{{ item }}"
    mode: 0755
    owner: root
    group: root
  with_items:
    - templates

- name: Show prometheus hosts
  debug:
    msg: "Prometheus hosts are: {{ groups[prometheus_inventory_group] }}"

- name: Ensure templates files
  copy:
    src: "{{ item }}"
    dest: "{{ prometheus_config_dir }}/templates/{{ item | basename }}"
    mode: 0644
    owner: root
    group: root
  # Fileglob always operates started from 'files' dir, so move to 'templates'
  # explicitly
  with_fileglob:
    - templates/*.yml
  notify:
    - Reload prometheus

- name: Ensure configuration file
  template:
    src: prometheus/prometheus.yml.j2
    dest: "{{ prometheus_config_dir }}/prometheus.yml"
    mode: 0755
    owner: root
    group: root
  register: prom_config

- name: Check prometheus config
  shell:
    cmd: |
      docker run --rm --entrypoint /bin/promtool -v {{ prometheus_config_dir }}:/tmp/prometheus {{ prometheus_docker_image }} check config /tmp/prometheus/prometheus.yml
  when:
    - prom_config.changed
  notify:
    - Reload prometheus

- name: Start docker prometheus container
  community.docker.docker_compose:
    state: present
    project_name: prometheus
    definition:
      version: '2'
      services:
        prometheus:
          image: "{{ prometheus_docker_image }}"
          container_name: "{{ prometheus_container_name }}"
          ports:
            - "127.0.0.1:9090:9090"
          volumes:
            - "{{ prometheus_config_dir }}/:/etc/prometheus/"
          hostname: "{{ prometheus_container_name }}"
          restart: always
          labels: "{{ prometheus_docker_labels }}"
          command:
            - "--config.file=/etc/prometheus/prometheus.yml"
            - "--storage.tsdb.path=/prometheus"
            - "--web.console.libraries=/usr/share/prometheus/console_libraries"
            - "--web.console.templates=/usr/share/prometheus/consoles"
            - "--web.enable-admin-api"
            - "--web.enable-lifecycle"
            - "--storage.tsdb.retention.time=7d"
      networks:
        default:
          external:
            name: "{{ prometheus_docker_network_name }}"
